INFO     common.recordlog:conftest.py:23 -----------------接口测试开始---------------------
INFO     common.recordlog:sendrequests.py:32 接口名称：新增用户
INFO     common.recordlog:sendrequests.py:33 接口请求地址：http://127.0.0.1:8787/dar/user/addUser
INFO     common.recordlog:sendrequests.py:34 测试用例名称：异常新增用户校验
INFO     common.recordlog:sendrequests.py:35 请求头：{'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'}
INFO     common.recordlog:sendrequests.py:36 cookies：None
INFO     common.recordlog:sendrequests.py:42 请求参数：{'data': {'username': 'testadduser', 'password': 'tset6789890', 'role_id': 123456789, 'dates': '2023-07-21 23:55:15', 'phone': 13800000000, 'token': 'ffe611F6f4854d4f6faca13Df8268'}}
INFO     common.recordlog:sendrequests.py:26 接口返回信息：{
  "error_code": null,
  "msg": "新增成功",
  "msg_code": 200
}

INFO     common.recordlog:assertions.py:90 yaml文件的预期结果：[{'contains': {'status_code': 200}}, {'contains': {'msg': '新增失败'}}]
ERROR    common.recordlog:assertions.py:46 响应文本断言失败：预期结果为【新增失败】,实际结果为【新增成功】
ERROR    common.recordlog:assertions.py:112 测试失败
ERROR    common.recordlog:apiutil.py:115
INFO     common.recordlog:conftest.py:25 -----------------接口测试结束---------------------
INFO     common.recordlog:test_debug_api.py:52 正在清理测试数据....